name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          override: true
          default: true
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      - name: Pull Docker image
        run: |
          sudo ctr i pull --all-platforms --all-metadata docker.io/library/alpine:latest
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features
